# Generated by Django 4.0.3 on 2022-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField()),
                ('clicks', models.PositiveIntegerField()),
                ('costs', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
